# Using Data Science to Prevent Potholes {#Preventing-Potholes}

#### Keywords {-}

Potholes, Urban, Data Science

## Nuisances of the Road

Potholes. These are nuisances that the everyday driver would have to dodge or else suffer an uncomfortable bump and the unease of possible damage done to their tires or rims. But a popped tire is the lease of our problems when driving through a large pothole at the right speed may cause potentially fatal accidents. Currently there is a system where government officials would eventually send workers to fix the potholes that are reported to them. However, usually potholes aren't reported and fixed until they have gotten big enough to affect the driver. By then, it is already too late because the pothole has already started inconveniencing everyone. By leveraging data science, it is possible to predict when a pothole is going to form and preemptively find and fix them when they are still small or merely cracks in the road. Imagine driving in your city or town and never encountering a pothole large enough to bother you. This would keep the average person thrilled to be living in the area. Subsequently, the government official will also be benefited with enhanced popularity because he has improved the quality of life of his people. Furthermore, fixing a pothole when it is small would save a lot more money than fixing it when it gets big. Also, being able to predict where and when to look for potholes would potentially save a lot of money and resources from surveillance.  

## Sensors, sensors, sensors!

Before we can predict when a pothole will form, we must first understand how they are formed. As roads get old, they usually suffer a degree of wear and tear as cracks start to form. However, in colder climates, as water seeps into the roads and freeze, they will expand and subsequently compromise the integrity of the road much faster than usual. Many repetitions of this freeing and melting, combined with the weight of the cars passing over, will cause the road to weaken, crack and eventually form a pothole. Therefore, to predict when a pothole may form, we would need data on the weather, such as precipitation or snowfall. Temperature data would also be required to determine whether the water would freeze. On top of this, it would be useful to have access to the average traffic of the area. This can be done by using traffic cameras to determine the average number of cars driving on the road a day. Also, the number of trucks and busses can also be obtained in a similar way. This data might even be readily available because bus and truck routes are usually recorded. Other information such as the last date the road was inspected and repaired, the type of materials the road was paved with, and the frequency in which the road has to be repaired in the past would further enhance the data set. Using all this data, a model can be developed to predict when a pothole may form so that officials can survey the road and fix any small potholes or cracks before they mature into a hindrance. Roads can also be ranked by priority in terms of the likelihood of developing potholes as well as the density of the traffic on that road. Hopefully, the resulting data driven model would be able to develop a system to determine which roads are due for a pothole inspection. This way, surveillance is only done when necessary, saving time and resources, but at the same time done early enough so that no pothole gets big enough to bother the drivers. 


```{r experimental,echo=F,results='asis',eval=F}
data.table::fread('https://raw.githubusercontent.com/UCB-MIDS/experiments-causality/master/data/GerberGreenBook_Chapter3_Donations.csv?token=ABNmuX-Q14rzQ4teItDenc9L5Wo2flncks5ZL5qEwA%3D%3D') %>% stargazer::stargazer(type = 'html',title = 'Something from W241 Experiments and Causality')
```


## All about efficiency and Premptive strikes.

When potholes form, how long does it take for the officials to notice and come and fix it? Is it cheaper or easier to fix cracks before big potholes form or is it easier to fix them after they're big? it is safer to fix them when they're small. How do government officials know to come fix the pothole? Do people report them? They have to be pretty big for people to take notice and report them. It will make people happy if they stop running into big potholes. Also it will be good for everyone's safety.